### ISSUE TITLE
soapaction path

### ISSUE THREAD

**Issue by jgibler** [kwhinnery/Suds#1]
I tried using sudsclient with a WCF service and had some problems when the path to the SoapAction is not necesarilly namespace/soapaction. In my case, I had something like: namespace/somepath/soapaction.  I added some code to the suds client to accept the optional parameter soapActionPath and in case it is set, the soapaction for the http post is generated correctly. Where can I share this code?

**Comment by kwhinnery** [comment]
if you send it to kwhinnery at appcelerator dot com I can throw it in (if you're not a github user)

**Comment by vinceyoumans** [comment]
did you ever submit this code?  is it working with DOT.NET services?

**Comment by kwhinnery** [comment]
It has been used with several .NET back ends.
