### ISSUE TITLE
Uncaught ReferenceError: obj is not defined

### ISSUE THREAD

**Issue by miwillhite** [kwhinnery/Suds#4]
Running the `invoke()` on a `SudsClient` causes this error: 
`Uncaught ReferenceError: obj is not defined`

Changing Line 14 to `original` instead of `obj`.

**Comment by dawsontoth** [comment]
Fixed by https://github.com/kwhinnery/Suds/pull/6 -- should be safe to close this, @miwillhite or @kwhinnery.
